MY_ROOMS = [
    "E8S92",
    "E7S93"
];

ALT_SOURCE_OPEN_SPOTS = 1;

ROLE = {
    HARVEST: "harvester",
    UPGRADE: "upgrader",
    BUILD: "repairer",
    HAUL: "transferer",
    SCOUT: "scout",
    SWARM: "swarm",
	REMOTE_RESERVE: "r_reserver",
	REMOTE_HARVEST: "r_harvester",
    REMOTE_DEFEND: "r_defender"
};

SOURCE_CONTAINERS = [
    "58eeba354601c18b200325a4",
    "58f40d8887d0acae4ed958bd",
    "58f547e61d3c63967872266d",
    "58f8a16ee4baf3cb7ed4cedd"
];

COLOUR = {
    BLACK:"#000000",
    GREY:"#808080",
    SILVER:"#C0C0C0",
    WHITE:"#FFFFFF",
    MAROON:"#800000",
    RED:"#FF0000",
    OLIVE:"#808000",
    YELLOW:"#FFFF00",
    GREEN:"#008000",
    LIME:"#00FF00",
    TEAL:"#008080",
    AQUA:"#00FFFF",
    NAVY:"#000080",
    BLUE:"#0000FF",
    PURPLE:"#800080",
    FUCHSIA:"#FF00FF"
};

UNIT_MAX = {
    "Spawn1": {
        HARVEST: 2,
        UPGRADE: 1,
        BUILD: 1,
        HAUL: 3,
        SCOUT: 0,
        SWARM: 0,
        REMOTE_RESERVE: 1,
        REMOTE_HARVEST: 2,
        REMOTE_DEFEND: 1
    },
    "Spawn2": {
        HARVEST: 2,
        UPGRADE: 2,
        BUILD: 1,
        HAUL: 2,
        SCOUT: 0,
        SWARM: 0,
        REMOTE_RESERVE: 0,
        REMOTE_HARVEST: 0,
        REMOTE_DEFEND: 1
    }
};

UNIT_COLOUR_IN = {
    HARVEST: COLOUR.BLACK,
    UPGRADE: COLOUR.SILVER,
    BUILD: COLOUR.MAROON,
    HAUL: COLOUR.OLIVE,
    SCOUT: COLOUR.GREEN,
    REMOTE_DEFEND: COLOUR.TEAL
};

UNIT_COLOUR_OUT = {
    HARVEST: COLOUR.GREY,
    UPGRADE: COLOUR.WHITE,
    BUILD: COLOUR.RED,
    HAUL: COLOUR.YELLOW,
    SCOUT: COLOUR.LIME,
    REMOTE_DEFEND: COLOUR.AQUA
};

UNIT = {
	"300" : {
		HARVEST: [MOVE,MOVE,WORK,CARRY,CARRY],
		UPGRADE: [MOVE,MOVE,WORK,CARRY,CARRY],
		BUILD: [MOVE,MOVE,WORK,CARRY,CARRY],
		HAUL: [MOVE,MOVE,CARRY,CARRY,CARRY,CARRY],
		SCOUT: [MOVE, MOVE, MOVE, RANGED_ATTACK],
		SWARM: [MOVE],
        REMOTE_RESERVE: null,
        REMOTE_DEFEND: null
	},
	"550" : {
		HARVEST: [MOVE,MOVE,MOVE,WORK,WORK,WORK,CARRY,CARRY],
		UPGRADE: [MOVE,MOVE,MOVE,WORK,WORK,WORK,CARRY,CARRY],
		BUILD: [MOVE,MOVE,MOVE,WORK,WORK,WORK,CARRY,CARRY],
		HAUL: [MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		SCOUT: [MOVE,MOVE,MOVE,MOVE,MOVE,RANGED_ATTACK],
		SWARM: [MOVE],
        REMOTE_RESERVE: null,
        REMOTE_DEFEND: null
	},
	"800" : {
		HARVEST: [MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY],
		UPGRADE: [MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY],
		BUILD: [MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY],
		HAUL: [MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		SCOUT: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,RANGED_ATTACK,RANGED_ATTACK],
		SWARM: [MOVE],
        REMOTE_RESERVE: [CLAIM, MOVE, MOVE],
        REMOTE_DEFEND: [TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,ATTACK,ATTACK,RANGED_ATTACK,RANGED_ATTACK]
	},
	"1300" : {
		HARVEST: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		UPGRADE: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		BUILD: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		HAUL: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		SCOUT: [TOUGH,TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK],
		SWARM: [MOVE],
        REMOTE_RESERVE: [CLAIM, CLAIM, MOVE, MOVE],
        REMOTE_DEFEND: [TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,ATTACK,ATTACK,RANGED_ATTACK,RANGED_ATTACK]
	},
	"1800" : {
		HARVEST: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		UPGRADE: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		BUILD: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		HAUL: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		SCOUT: [TOUGH,TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK],
		SWARM: [MOVE],
        REMOTE_RESERVE: [CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE],
        REMOTE_DEFEND: [TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,ATTACK,ATTACK,RANGED_ATTACK,RANGED_ATTACK]
	},
	"2300" : {
		HARVEST: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		UPGRADE: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		BUILD: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		HAUL: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		SCOUT: [TOUGH,TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK],
		SWARM: [MOVE],
        REMOTE_RESERVE: [CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
        REMOTE_DEFEND: [TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,ATTACK,ATTACK,RANGED_ATTACK,RANGED_ATTACK]
	},
	"5600" : {
		HARVEST: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		UPGRADE: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		BUILD: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		HAUL: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		SCOUT: [TOUGH,TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK],
		SWARM: [MOVE],
        REMOTE_RESERVE: [CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
        REMOTE_DEFEND: [TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,ATTACK,ATTACK,RANGED_ATTACK,RANGED_ATTACK]
	},
	"12900" : {
		HARVEST: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		UPGRADE: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		BUILD: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		HAUL: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY],
		SCOUT: [TOUGH,TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK],
		SWARM: [MOVE],
        REMOTE_RESERVE: [CLAIM, CLAIM, CLAIM, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
        REMOTE_DEFEND: [TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,ATTACK,ATTACK,RANGED_ATTACK,RANGED_ATTACK]
	}
};


MY_FRIENDS = [
    "Zarakk"
];

SCOUT_DIRECTION = {
    EAST: "east",
    WEST: "west"
};

SCOUT_ROOMS = {
    WEST: [
        "E7S93"
    ],
    EAST: [
        "E7S93"
    ]
};